### PR TITLE
Remove IANA registry

### PR DESCRIPTION
**Pull request by wtoorop**
Cherry picked from  PR #12

### CODE REVIEW

**Comment by oerdnj** [comment]
I think we should keep the registry. The dnsop group might provide some guidance if this is not desirable.

**Comment by TeamShadowHunters** [comment]
Donald thinks so too:

> On the IANA Registry, it used to be fine to not bother setting up a registry when you first defined a field and one or a few initial values. You could set it up later the first time you added more values. But increasingly I have found that the IESG (or rather some members of the IESG) like to have a registry set up from the beginning. True, the registry is not just of hash functions but also of the construction technique, but that's fine.

**Comment by wtoorop** [comment]
I think so too and I have confirmation from Donald that he thinks we should keep it too

**Comment by wtoorop** [comment]
Archiving

**Pull request closed without merging**
